# Generated by Django 4.2.3 on 2023-07-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopolls', '0004_alter_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
