# Generated by Django 4.2.3 on 2023-07-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogirls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='djangogirls.tags'),
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
