# Generated by Django 4.2.3 on 2023-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogirls', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_file',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
