# Generated by Django 4.2.3 on 2023-07-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogirls', '0002_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
