# Generated by Django 4.2.3 on 2023-07-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogirls', '0002_alter_post_tags_delete_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='post_tag', to='djangogirls.tags'),
        ),
    ]
