# Generated by Django 4.2.3 on 2023-07-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogirls', '0003_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature_img',
            field=models.ImageField(blank=True, null=True, upload_to='featureimg/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postimg/'),
        ),
    ]
