# Generated by Django 4.2.4 on 2023-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogirls', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
