# Generated by Django 4.2.3 on 2023-07-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogirls', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='feature_img',
            field=models.ImageField(blank=True, upload_to='featureimg/'),
        ),
    ]
