# Generated by Django 4.2.3 on 2023-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogirls', '0007_alter_comment_options_post_feature_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.PositiveIntegerField(max_length=10, unique=True),
        ),
    ]
